### ISSUE TITLE
Where is counsel-mode?

### ISSUE THREAD

**Issue by c02y** [clemera/ivy-explorer#10]
I tried to paste 

    (counsel-mode 1)

into my init.el

but it says

    Symbol's function definition is void: counsel-mode

**Comment by clemera** [comment]
`counsel-mode` is not included in `ivy-explorer` you need to install it separately if you want to use it. See [swiper](https://github.com/abo-abo/swiper).

**Comment by c02y** [comment]
Oh, you should mention that.

After I installed `counsel` package, the error is gone.

**Comment by clemera** [comment]
Note that you don't need to use counsel it is optional.

**Comment by c02y** [comment]
Then, what it is for?

**Comment by clemera** [comment]
It provides specialized commands using `ivy` and comes with the swiper package I linked above.
