### ISSUE TITLE
counsel-explorer fails when filenames contain percentage character %

### ISSUE THREAD

**Issue by BibleBelt** [clemera/ivy-explorer#5]
If the directory where you start the counsel-explorer command contains at least one file that has a percentage sign (%) in it's name, cousel-explorer fails and prints

apply: Not enough arguments for format string

into the mini buffer.

If I start from a different directory then counsel-explorer fails in a similar manner, whenever I change into a directory that contains the offending file names. This time it prints

Error in post-command-hook (ivy--queue-exhibit): (error "Not enough arguments for format string")

into the mini buffer. 

OS: CentOS Linux release 7.5.1804
emacs: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-05-30
ivy:  ivy-20181223.2002
ivy-explorer: ivy-explorer-20181221.1227

Update: A similar thing happens when a file name contains the hash character # 
This time the error reads:

ivy-explorer--display-function: Arithmetic error

**Comment by clemera** [comment]
Thanks, for the report. It should be fixed now!

**Comment by BibleBelt** [comment]
Yep, it's fixed. Thanks a lot.
