### ISSUE TITLE
Very nice.  Following Ctrl-a, Ctrl-e would be even nicer

### ISSUE THREAD

**Issue by notuntoward** [clemera/ivy-explorer#6]
I really like this extension.  One small improvement would be if Ctrl-a and Ctrl-e brought the cursor to the left and right columns.  That's what my finger memory did immediately when I tried ivy-explorer, and I'd guess that other emacs users would do the same.

**Comment by clemera** [comment]
I wanted to add this for a while, thanks for the nudge! Could you give it some testing?

**Comment by notuntoward** [comment]
Sure, I'm using now.

Thanks,

Scott
