### ISSUE TITLE
How to use the navigate keys?

### ISSUE THREAD

**Issue by c02y** [clemera/ivy-explorer#9]
In the README:

    Users can navigate the grid using `Ctrl-f`, `Ctrl-b`, `Ctrl-n`, `Ctrl-p`, `Ctrl-a`, `Ctrl-e`.

`C-e` and `C-a` work, which go the the ending/beginning of string I typed.

But the other keys don't work at all. How exactly can I use them?

**Comment by clemera** [comment]
`C-a` and `C-e` should navigate to first/last column in the grid not in the string you typed. I'm not sure what's wrong could you please post you config?

**Comment by c02y** [comment]
(ivy-explorer-mode 1)

**Comment by clemera** [comment]
What about ivy-mode and counsel-mode could you please post the order in which you call them?

**Comment by c02y** [comment]
I'll calling `M-x find-file` directly not `C-x C-f`, since I failed to enable `counsel-mode`(check my another issue)

I din't enable `ivy-mode` since I use `helm`

**Comment by c02y** [comment]
After I enable `ivy-mode` and `counsel-mode`.

The keys are still not working.

**Comment by clemera** [comment]
What does `C-h k C-f` show you?

**Comment by c02y** [comment]
You mean the `C-f` when using `ivy-explorer`? It is bound to `ivy-explorer-forward`.

**Comment by c02y** [comment]
FYI:

I'm binding `C-e` and `C-a` using `bind-keys*` in my init.el, I believe that is why they are working, even thought they not working as you want.

**Comment by clemera** [comment]
>  I believe that is why they are working

Yey bind-keys* overrides all other bindings, you probably don't want to use it for keys like `C-a` and `C-e` many modes rebind those and you won't get them this way.

>  `C-f` is bound to ivy-explorer-forward

Ok, so that's the right command. And it does nothing? That is strange, do you use any other minor-modes or settings for minibuffer commands?

**Comment by clemera** [comment]
Also do you see the grid at all?

**Comment by c02y** [comment]
No grid, I got a lot of configuration, don't know what affects it.

Another thing is, if I don't set `(counsel-mode 1)` in my init.el since you said it is optional, and now
`C-x C-f` gives error message

    Symbol's function definition is void: counsel-find-file


I give up since I don't use ivy/swiper/counsel at all.

**Comment by clemera** [comment]
Sorry for that! Seems to be a configuration issue indeed.
